OV7251 Support V1
linux-surface/kernel pull request #118
Opened 2022-02-22 23:56 UTC by djrscally

This series enables the IR sensor on the Surface line at a fairly basic level. Additional work will be needed to enable the IR LED that help to illuminate the user when taking images and to allow streaming through libcamera, but this series is sufficient to take images with the sensor, so I wanted to share it now (not least because more testers is always a good thing...)

2022-02-23 04:01 UTC, qzed requested changes
Awesome! Looks mostly good to me, can't speak for the functionality though as I'm still pretty unfamiliar with the media subsystem, so I assume all that checks out.

I've found small issue, however.

2022-02-23 23:22 UTC, djrscally commented on drivers/media/i2c/ov7251.c
> +			return ret;
Good spot! Thank you - I'll fix it.

2022-08-10 16:14 UTC, qzed commented
@djrscally I assume this is no longer needed with v5.19, which seems to include at least some ov7251 stuff?

2022-08-12 08:40 UTC, djrscally commented
Yeah this can go - sorry, forgot it was even open

2022-08-12 09:37 UTC, qzed commented
No worries.

2022-08-12 09:37 UTC, closed without merging