ov5693: Add user controls to flip image
linux-surface/kernel pull request #75
Opened 2020-12-28 22:02 UTC by fabwu

Add V4L2_CID_HFLIP and V4L2_CID_VFLIP to support flipping the image on the sensor side.

The ipu3 pipeline in libcamera is not ready to handle these controls yet.

2020-12-29 22:58 UTC, qzed requested changes
Thanks, looks good overall, but there are a couple of style issues (e.g. spaces instead of tabs for indentation and things like that). Would you mind running `checkpatch --strict` on the patch and fix those?

2020-12-30 17:43 UTC, fabwu commented
@qzed Thanks for the review. I fixed the style issues in my changes but the driver has more of them. Should I create a separate PR to fix these issues as well?

2020-12-30 22:33 UTC, qzed approved these changes

2020-12-30 22:34 UTC, qzed commented
Thanks!

> I fixed the style issues in my changes but the driver has more of them. Should I create a separate PR to fix these issues as well?

That'd be great if you have the time for it.

2020-12-30 22:35 UTC, merged